# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8BL5G_cX49c8iDF4dhFewsbz84qBKvx
"""

import numpy as np
arr=np.array([1,2,3,4])
print(arr)

import numpy as np
arr_zeroes=np.zeros(3)
print(arr_zeroes)

import numpy as np
arr_ones=np.ones((3,3))
print(arr_ones)

import numpy as np
arr_filling=np.full((3,3),7)
print(arr_filling)

import numpy as np
arr_arange=np.arange(1,10,2)
print(arr_arange)

import numpy as np
id_matrices=np.eye(3)
print(id_matrices)

